### PR TITLE
Assignment 2

### PR DESCRIPTION
**Pull request by kellywslee**

### CODE REVIEW

**Comment by aanglin07** [comment]
Hi Kelly.

The color scheme of your App looks really good. It has a nice clean feel to it.

While exploring the App I noticed a few things regarding its usability . Maybe you are still working on these things but I will still highlight it, just in case.

1. Home Page.

- To supplement the drop down menu in the Navbar. There could be a link on the main page to take users to the Find doggie playdates. I didn't readily know where to go to start searching for a playdate when I loaded the App. A simple "here" at end of "Find doggie playdates!" that navigates to the search page should suffice.

2. Filtering by checkbox.

-  I am only able to see two dogs at a time no matter the filter selected. Could be a scrolling issue.
- I noticed that when I clicked the energy level options, clicking on multiple checkboxes, didn't return dogs with both filters. 
 The first checkbox filter criteria was being populated. 

- Consider using radio buttons that handles the change in selected filters for energy levels. Unless its a scrolling issue, because I 
was only able to see a max of two dogs with the first energy level selected given priority.

Hopefully this feedback was helpful.

**Review by aanglin07 — COMMENTED** [review]
Hi Kelly.

The color scheme of your App looks really good. It has a nice clean feel to it.

While exploring the App I noticed a few things regarding its usability . Maybe you are still working on these things but I will still highlight it, just in case.

Home Page.
To supplement the drop down menu in the Navbar. There could be a link on the main page to take users to the Find doggie playdates. I didn't readily know where to go to start searching for a playdate when I loaded the App. A simple "here" at end of "Find doggie playdates!" that navigates to the search page should suffice.
Filtering by checkbox.
I am only able to see two dogs at a time no matter the filter selected. Could be a scrolling issue.

I noticed that when I clicked the energy level options, clicking on multiple checkboxes, didn't return dogs with both filters.
The first checkbox filter criteria was being populated.

Consider using radio buttons that handles the change in selected filters for energy levels. Unless its a scrolling issue, because I
was only able to see a max of two dogs with the first energy level selected given priority.

Hopefully this feedback was helpful.

**Comment by kellywslee** [comment]
> Hi Kelly.
> 
> The color scheme of your App looks really good. It has a nice clean feel to it.
> 
> While exploring the App I noticed a few things regarding its usability . Maybe you are still working on these things but I will still highlight it, just in case.
> 
> 1. Home Page. 
> 
> * To supplement the drop down menu in the Navbar. There could be a link on the main page to take users to the Find doggie playdates. I didn't readily know where to go to start searching for a playdate when I loaded the App. A simple "here" at end of "Find doggie playdates!" that navigates to the search page should suffice.
> 
> 2. Filtering by checkbox.
> 
> * I am only able to see two dogs at a time no matter the filter selected. Could be a scrolling issue.
> * I noticed that when I clicked the energy level options, clicking on multiple checkboxes, didn't return dogs with both filters. The first checkbox filter criteria was being populated.
> * Consider using radio buttons that handles the change in selected filters for energy levels. Unless its a scrolling issue, because I was only able to see a max of two dogs with the first energy level selected given priority.
> 
> Hopefully this feedback was helpful.

Thanks Anthony!

1. ✅👍😃 wow this is a great idea!! I will implement this for sure.
2.  The scroll bar is hidden, but you will be able to scroll when you see a hand pointer. I think I should improve UX. 😅 Filters are working find for me though. 🤔

image

**Comment by aanglin07** [comment]
- For some reason, I am not seeing or able to scroll on the search return area for the dogs. Maybe I am doing something wrong.
- The filter works but I am only able to see two dogs at a time on my end.
Screenshot 2023-08-11 233444

**Comment by topiwalaj** [comment]
Hi Kelly

Your app looks really nice. The Design looks like it is a real website. Great work :) 

The find playdates filter dose not work for me. May be I need to run other command as well.

But overall great work Kelly.

**Comment by kellywslee** [comment]
Hi Jigi,

Thank your for your feedback. You have to run ‘npm run server’ to load the
data. 😄

**Comment by samihasher** [comment]
Kelly,

Your web app looks great! It functions really well overall. Your code was easy to read and to follow, I love the organization of folders.

I like the change from the postal code box to the map - super cool feature!

One suggestion for usability:
- When searching "20 lb" and "Moderate" no dogs show up, maybe adding a message saying "search again" so the user doesn't have to make logical leaps to uncheck the boxes

**Comment by kellywslee** [comment]
> * "20 lb" and "Moderate

Wow! that's a great suggestion. Thank you! 😃

**Pull request merged**
